# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'johnwatson484'
    scannerMode: 'MSBuild'
    projectKey: 'johnwatson484_team-picker'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.sln'
    arguments: '-p:AndroidKeyStore=true -p:AndroidSigningKeyStore=KeyStore.keystore -p:AndroidSigningKeyAlias=TeamPicker -p:AndroidSigningKeyPass=env:$(keyStorePassword) -p:AndroidSigningStorePass=$(keyStorePassword)'
    zipAfterPublish: false

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'