#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TeamPicker.Resource", IsApplication=true)]

namespace TeamPicker
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.99")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ServiceStack.Pcl.Android.Resource.String.ApplicationName = global::TeamPicker.Resource.String.ApplicationName;
			global::ServiceStack.Pcl.Android.Resource.String.Hello = global::TeamPicker.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int alpha = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int buttonSize = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int colorScheme = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int coordinatorLayoutStyle = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int font = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontProviderAuthority = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontProviderCerts = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontProviderFetchStrategy = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int fontProviderFetchTimeout = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int fontProviderPackage = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int fontProviderQuery = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int fontStyle = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int fontVariationSettings = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int fontWeight = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int imageAspectRatioAdjust = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int keylines = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int layout_anchor = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int layout_anchorGravity = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int layout_behavior = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int layout_dodgeInsetEdges = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int layout_insetEdge = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int layout_keyline = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int scopeUris = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int statusBarBackground = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int ttcIndex = 2130771997;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int browser_actions_bg_grey = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int browser_actions_divider_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int browser_actions_text_color = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int browser_actions_title_color = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int common_google_signin_btn_text_dark = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int common_google_signin_btn_text_dark_default = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int common_google_signin_btn_text_dark_disabled = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int common_google_signin_btn_text_dark_focused = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int common_google_signin_btn_text_dark_pressed = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int common_google_signin_btn_text_light = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int common_google_signin_btn_text_light_default = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int common_google_signin_btn_text_light_disabled = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int common_google_signin_btn_text_light_focused = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int common_google_signin_btn_text_light_pressed = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int common_google_signin_btn_tint = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int notification_action_color_filter = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int notification_icon_bg_color = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int notification_material_background_media_default_color = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int primary_text_default_material_dark = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int ripple_material_light = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int secondary_text_default_material_dark = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int secondary_text_default_material_light = 2130837525;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int browser_actions_context_menu_max_width = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int browser_actions_context_menu_min_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_inset_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_inset_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_button_padding_horizontal_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_button_padding_vertical_material = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_control_corner_material = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int compat_notification_large_icon_max_height = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int compat_notification_large_icon_max_width = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int notification_action_icon_size = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_action_text_size = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_big_circle_margin = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_content_margin_start = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_large_icon_height = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_large_icon_width = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_main_column_padding_top = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_media_narrow_margin = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_right_icon_size = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_right_side_padding_top = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_small_icon_background_padding = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_small_icon_size_as_large = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_subtext_size = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int notification_top_pad = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int notification_top_pad_large_text = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int subtitle_corner_radius = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int subtitle_outline_width = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int subtitle_shadow_offset = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int subtitle_shadow_radius = 2130903067;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int common_full_open_on_phone = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int common_google_signin_btn_icon_dark = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int common_google_signin_btn_icon_dark_focused = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int common_google_signin_btn_icon_dark_normal = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int common_google_signin_btn_icon_disabled = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int common_google_signin_btn_icon_light = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int common_google_signin_btn_icon_light_focused = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int common_google_signin_btn_icon_light_normal = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int common_google_signin_btn_icon_light_normal_background = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int common_google_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int common_google_signin_btn_text_dark_focused = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int common_google_signin_btn_text_dark_normal = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int common_google_signin_btn_text_dark_normal_background = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int common_google_signin_btn_text_disabled = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int common_google_signin_btn_text_light = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int common_google_signin_btn_text_light_focused = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int common_google_signin_btn_text_light_normal = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int common_google_signin_btn_text_light_normal_background = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int googleg_disabled_color_18 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int googleg_standard_color_18 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int ic_clear_white_24dp = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int ic_delete_white_24dp = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int ic_history_white_24dp = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int ic_launcher = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int ic_person_add_white_24dp = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int ic_settings_white_24dp = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int ic_share_white_24dp = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int notification_action_background = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int notification_bg = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int notification_bg_low = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int notification_bg_low_normal = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int notification_bg_low_pressed = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int notification_bg_normal = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int notification_bg_normal_pressed = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int notification_icon_background = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int notification_template_icon_bg = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int notification_template_icon_low_bg = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int notification_tile_bg = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int notify_panel_notification_icon_bg = 2130968615;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action0 = 2131034112;
			
			// aapt resource value: 0x7F050005
			public const int actions = 2131034117;
			
			// aapt resource value: 0x7F050001
			public const int action_container = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int action_divider = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int action_image = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int action_text = 2131034116;
			
			// aapt resource value: 0x7F050007
			public const int adjust_height = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int adjust_width = 2131034120;
			
			// aapt resource value: 0x7F050006
			public const int adView = 2131034118;
			
			// aapt resource value: 0x7F050009
			public const int all = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int async = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int auto = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int blocking = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int bottom = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int browser_actions_header_text = 2131034126;
			
			// aapt resource value: 0x7F050011
			public const int browser_actions_menu_items = 2131034129;
			
			// aapt resource value: 0x7F05000F
			public const int browser_actions_menu_item_icon = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int browser_actions_menu_item_text = 2131034128;
			
			// aapt resource value: 0x7F050012
			public const int browser_actions_menu_view = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int btnCancelMatch = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int btnCancelMatchList = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int btnCancelPlayer = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int btnCancelPrivacy = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int btnCancelSettings = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int btnCreatePlayer = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int btnDeleteMatch = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int btnDeletePlayer = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int btnMatchHistory = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int btnMatchRePick = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int btnMatchSave = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int btnPickTeams = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int btnSavePlayer = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int btnSaveSettings = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int btnSettings = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int btnShareMatch = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int cancel_action = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int center = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int center_horizontal = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int center_vertical = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int chkAllPlayers = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int chkPlayer = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int chkUniqueRole = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int chronometer = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int clip_horizontal = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int clip_vertical = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int dark = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int end = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int end_padder = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int fill = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int fill_horizontal = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int fill_vertical = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int forever = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int icon = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int icon_group = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int icon_only = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int info = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int italic = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int left = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int light = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int line1 = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int line3 = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int listMatches = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int listPlayers = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int listTeams = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int matchNumber = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int media_actions = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int none = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int normal = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int notes = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int notification_background = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int notification_main_column = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int notification_main_column_container = 2131034183;
			
			// aapt resource value: 0x7F050048
			public const int numMaxRating = 2131034184;
			
			// aapt resource value: 0x7F050049
			public const int numNumberOfTeams = 2131034185;
			
			// aapt resource value: 0x7F05004A
			public const int numRatingInput = 2131034186;
			
			// aapt resource value: 0x7F05004B
			public const int playerName = 2131034187;
			
			// aapt resource value: 0x7F05004C
			public const int radioGroup1 = 2131034188;
			
			// aapt resource value: 0x7F05004D
			public const int rating = 2131034189;
			
			// aapt resource value: 0x7F05004E
			public const int rbAlphabetical = 2131034190;
			
			// aapt resource value: 0x7F05004F
			public const int rbMostSelected = 2131034191;
			
			// aapt resource value: 0x7F050050
			public const int rbRating = 2131034192;
			
			// aapt resource value: 0x7F050051
			public const int relativeLayout1 = 2131034193;
			
			// aapt resource value: 0x7F050052
			public const int relativeLayout2 = 2131034194;
			
			// aapt resource value: 0x7F050053
			public const int right = 2131034195;
			
			// aapt resource value: 0x7F050054
			public const int right_icon = 2131034196;
			
			// aapt resource value: 0x7F050055
			public const int right_side = 2131034197;
			
			// aapt resource value: 0x7F050056
			public const int selectedNumber = 2131034198;
			
			// aapt resource value: 0x7F050057
			public const int selectedText = 2131034199;
			
			// aapt resource value: 0x7F050058
			public const int splashDeveloper = 2131034200;
			
			// aapt resource value: 0x7F050059
			public const int splashIcon = 2131034201;
			
			// aapt resource value: 0x7F05005A
			public const int splashTitle = 2131034202;
			
			// aapt resource value: 0x7F05005B
			public const int standard = 2131034203;
			
			// aapt resource value: 0x7F05005C
			public const int start = 2131034204;
			
			// aapt resource value: 0x7F05005D
			public const int status_bar_latest_event_content = 2131034205;
			
			// aapt resource value: 0x7F05005E
			public const int swBalance = 2131034206;
			
			// aapt resource value: 0x7F05005F
			public const int swDisplayNotes = 2131034207;
			
			// aapt resource value: 0x7F050060
			public const int swHighAccuracy = 2131034208;
			
			// aapt resource value: 0x7F050061
			public const int swTrafficLightRatings = 2131034209;
			
			// aapt resource value: 0x7F050062
			public const int tag_transition_group = 2131034210;
			
			// aapt resource value: 0x7F050063
			public const int tag_unhandled_key_event_manager = 2131034211;
			
			// aapt resource value: 0x7F050064
			public const int tag_unhandled_key_listeners = 2131034212;
			
			// aapt resource value: 0x7F050065
			public const int teamScore = 2131034213;
			
			// aapt resource value: 0x7F050066
			public const int text = 2131034214;
			
			// aapt resource value: 0x7F050067
			public const int text2 = 2131034215;
			
			// aapt resource value: 0x7F050068
			public const int time = 2131034216;
			
			// aapt resource value: 0x7F050069
			public const int title = 2131034217;
			
			// aapt resource value: 0x7F05006A
			public const int toolbarMatch = 2131034218;
			
			// aapt resource value: 0x7F05006B
			public const int toolbarMatchList = 2131034219;
			
			// aapt resource value: 0x7F05006C
			public const int toolbarMatchListTitle = 2131034220;
			
			// aapt resource value: 0x7F05006D
			public const int toolbarMatchTitle = 2131034221;
			
			// aapt resource value: 0x7F05006E
			public const int toolbarPlayer = 2131034222;
			
			// aapt resource value: 0x7F05006F
			public const int toolbarPlayerTitle = 2131034223;
			
			// aapt resource value: 0x7F050070
			public const int toolbarPrivacy = 2131034224;
			
			// aapt resource value: 0x7F050071
			public const int toolbarPrivacyTitle = 2131034225;
			
			// aapt resource value: 0x7F050072
			public const int toolbarSelection = 2131034226;
			
			// aapt resource value: 0x7F050073
			public const int toolbarSelectionTitle = 2131034227;
			
			// aapt resource value: 0x7F050074
			public const int toolbarSettings = 2131034228;
			
			// aapt resource value: 0x7F050075
			public const int top = 2131034229;
			
			// aapt resource value: 0x7F050076
			public const int txtBalanceTeams = 2131034230;
			
			// aapt resource value: 0x7F050077
			public const int txtDisplayNotes = 2131034231;
			
			// aapt resource value: 0x7F050078
			public const int txtHighAccuracy = 2131034232;
			
			// aapt resource value: 0x7F050079
			public const int txtMatchDate = 2131034233;
			
			// aapt resource value: 0x7F05007A
			public const int txtMatchTime = 2131034234;
			
			// aapt resource value: 0x7F05007B
			public const int txtMaxRating = 2131034235;
			
			// aapt resource value: 0x7F05007C
			public const int txtNoMatches = 2131034236;
			
			// aapt resource value: 0x7F05007D
			public const int txtNoPlayers = 2131034237;
			
			// aapt resource value: 0x7F05007E
			public const int txtNotes = 2131034238;
			
			// aapt resource value: 0x7F05007F
			public const int txtNotesLabel = 2131034239;
			
			// aapt resource value: 0x7F050080
			public const int txtNumberLimit = 2131034240;
			
			// aapt resource value: 0x7F050081
			public const int txtNumberOfTeams = 2131034241;
			
			// aapt resource value: 0x7F050082
			public const int txtPlayerName = 2131034242;
			
			// aapt resource value: 0x7F050083
			public const int txtPlayerNameInput = 2131034243;
			
			// aapt resource value: 0x7F050084
			public const int txtPlayerOrder = 2131034244;
			
			// aapt resource value: 0x7F050085
			public const int txtPrivacy = 2131034245;
			
			// aapt resource value: 0x7F050086
			public const int txtPrivacyDetails = 2131034246;
			
			// aapt resource value: 0x7F050087
			public const int txtRatingLabel = 2131034247;
			
			// aapt resource value: 0x7F050088
			public const int txtRatingLimit = 2131034248;
			
			// aapt resource value: 0x7F050089
			public const int txtSavedText = 2131034249;
			
			// aapt resource value: 0x7F05008A
			public const int txtScore = 2131034250;
			
			// aapt resource value: 0x7F05008B
			public const int txtSelectAll = 2131034251;
			
			// aapt resource value: 0x7F05008C
			public const int txtTeamName = 2131034252;
			
			// aapt resource value: 0x7F05008D
			public const int txtTeamPlayers = 2131034253;
			
			// aapt resource value: 0x7F05008E
			public const int txtTeamRating = 2131034254;
			
			// aapt resource value: 0x7F05008F
			public const int txtTeamScore = 2131034255;
			
			// aapt resource value: 0x7F050090
			public const int txtTotalPlayers = 2131034256;
			
			// aapt resource value: 0x7F050091
			public const int txtTrafficLightRatings = 2131034257;
			
			// aapt resource value: 0x7F050092
			public const int txtUniqueRole = 2131034258;
			
			// aapt resource value: 0x7F050093
			public const int uniqueRole = 2131034259;
			
			// aapt resource value: 0x7F050094
			public const int wide = 2131034260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int google_play_services_version = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int status_bar_notification_info_maxnum = 2131099650;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int browser_actions_context_menu_page = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int browser_actions_context_menu_row = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int Match = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MatchList = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int MatchListItem = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_action = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_action_tombstone = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_media_action = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_media_cancel_action = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_big_media = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_big_media_custom = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int notification_template_big_media_narrow = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int notification_template_big_media_narrow_custom = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int notification_template_custom_big = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int notification_template_icon_group = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int notification_template_lines_media = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int notification_template_media = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int notification_template_media_custom = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int notification_template_part_chronometer = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int notification_template_part_time = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int Player = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int PlayerListItem = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int Privacy = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int Selection = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int Settings = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int Splash = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int TeamItem = 2131165210;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080002
			public const int common_google_play_services_enable_button = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int common_google_play_services_enable_text = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int common_google_play_services_enable_title = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int common_google_play_services_install_button = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int common_google_play_services_install_text = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int common_google_play_services_install_title = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int common_google_play_services_notification_channel_name = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int common_google_play_services_notification_ticker = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int common_google_play_services_unknown_issue = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int common_google_play_services_unsupported_text = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int common_google_play_services_update_button = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int common_google_play_services_update_text = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int common_google_play_services_update_title = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int common_google_play_services_updating_text = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int common_google_play_services_wear_update_text = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int common_open_on_phone = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int common_signin_button_text = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int common_signin_button_text_long = 2131230739;
			
			// aapt resource value: 0x7F080001
			public const int Hello = 2131230721;
			
			// aapt resource value: 0x7F080014
			public const int s1 = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int s2 = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int s3 = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int s4 = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int s5 = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int s6 = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int s7 = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int status_bar_notification_info_overflow = 2131230747;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int TextAppearance_Compat_Notification_Info_Media = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int TextAppearance_Compat_Notification_Line2 = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int TextAppearance_Compat_Notification_Media = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int TextAppearance_Compat_Notification_Time = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int TextAppearance_Compat_Notification_Time_Media = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int TextAppearance_Compat_Notification_Title = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int TextAppearance_Compat_Notification_Title_Media = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int Theme_IAPTheme = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int Theme_MyTheme = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int Widget_Compat_NotificationActionContainer = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int Widget_Compat_NotificationActionText = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int Widget_Support_CoordinatorLayout = 2131296270;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002 }
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010003 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771971};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010014,0x7F01001C }
			public static int[] CoordinatorLayout = new int[] {
					2130771988,
					2130771996};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E }
			public static int[] FontFamily = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010008,0x7F01000F,0x7F010010,0x7F010011,0x7F01001D }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771976,
					2130771983,
					2130771984,
					2130771985,
					2130771997};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F010005,0x7F010012,0x7F010013 }
			public static int[] LoadingImageView = new int[] {
					2130771973,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public const int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010004,0x7F010006,0x7F01001B }
			public static int[] SignInButton = new int[] {
					2130771972,
					2130771974,
					2130771995};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
