#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TeamPicker.Resource", IsApplication=true)]

namespace TeamPicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ServiceStack.Pcl.Android.Resource.String.ApplicationName = global::TeamPicker.Resource.String.ApplicationName;
			global::ServiceStack.Pcl.Android.Resource.String.Hello = global::TeamPicker.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int ic_clear_white_24dp = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ic_delete_white_24dp = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ic_history_white_24dp = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_person_add_white_24dp = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ic_settings_white_24dp = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ic_share_white_24dp = 2130771974;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int adView = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int btnCancelMatch = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int btnCancelMatchList = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btnCancelPlayer = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btnCancelPrivacy = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int btnCancelSettings = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int btnCreatePlayer = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int btnDeleteMatch = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int btnDeletePlayer = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int btnMatchHistory = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int btnMatchRePick = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int btnMatchSave = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int btnPickTeams = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int btnSavePlayer = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int btnSaveSettings = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int btnSettings = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int btnShareMatch = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int chkAllPlayers = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int chkPlayer = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int chkUniqueRole = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int listMatches = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int listPlayers = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int listTeams = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int matchNumber = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int notes = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int numMaxRating = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int numNumberOfTeams = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int numRatingInput = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int playerName = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int radioGroup1 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int rating = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int rbAlphabetical = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int rbMostSelected = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int rbRating = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int relativeLayout1 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int relativeLayout2 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int selectedNumber = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int selectedText = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int splashDeveloper = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int splashIcon = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int splashTitle = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int swBalance = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int swDisplayNotes = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int swHighAccuracy = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int swTrafficLightRatings = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int teamScore = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int toolbarMatch = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int toolbarMatchList = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int toolbarMatchListTitle = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int toolbarMatchTitle = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int toolbarPlayer = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int toolbarPlayerTitle = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int toolbarPrivacy = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int toolbarPrivacyTitle = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int toolbarSelection = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int toolbarSelectionTitle = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int toolbarSettings = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int txtBalanceTeams = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int txtDisplayNotes = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int txtHighAccuracy = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int txtMatchDate = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int txtMatchTime = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int txtMaxRating = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int txtNoMatches = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int txtNoPlayers = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int txtNotes = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int txtNotesLabel = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int txtNumberLimit = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int txtNumberOfTeams = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int txtPlayerName = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int txtPlayerNameInput = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int txtPlayerOrder = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int txtPrivacy = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int txtPrivacyDetails = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int txtRatingLabel = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int txtRatingLimit = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int txtSavedText = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int txtScore = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int txtSelectAll = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int txtTeamName = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int txtTeamPlayers = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int txtTeamRating = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int txtTeamScore = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int txtTotalPlayers = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int txtTrafficLightRatings = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int txtUniqueRole = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int uniqueRole = 2130837590;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Match = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int MatchList = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int MatchListItem = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Player = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int PlayerListItem = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int Privacy = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int Selection = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int Splash = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int TeamItem = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int Theme_MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
